# **A Simple Neural Network Making a Prediction**

### **What is a Neural Network?** 

In [8]:
# The network:
weight = 0.2 
def neural_network(input, weight):
    prediction = input * weight
    return prediction

# How we use the network to predict something:
number_of_bedrooms = [3, 2, 4, 3, 5]
input = number_of_bedrooms[0]
pred = neural_network(input,weight)
print(pred)

0.6000000000000001


# **Making a Prediction with Multiple Inputs**

### **Complete Runnable Code**

In [23]:
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output
          #bedrooms_weight #bathrooms_weight, #floors_weight #cond_weight
weights = [0.2, 0.01, 0.2, -0.2] 
    
def neural_network(input, weights):
    pred = w_sum(input,weights)
    return pred

# This dataset is the housing 
# dataset of a society for 5 houses.

# bedrooms = number of bedrooms in a house
# bathrooms = number of bathrooms in a house
# floors = number of floors in a house
# condition = condition of house (higher the number worst the condition of house)

bedrooms =  [3, 2, 4, 3, 5]
bathrooms = [1, 1, 3, 2, 4]
floors = [1, 1, 2, 2, 1]
condition = [0.48, 0.85, 0.56, 0.2, 0.1]
# Input corresponds to every entry
# for the first game of the season.

input = [bedrooms[0], bathrooms[0], floors[0], condition[0]]
pred = neural_network(input,weights)
print(pred)

0.7140000000000001


### **NumPy Code**

In [24]:
import numpy as np
weights = np.array([0.2, 0.01, 0.2, -0.2])
def neural_network(input, weights):
    pred = input.dot(weights)
    return pred

bedrooms =  np.array([3, 2, 4, 3, 5])
bathrooms = np.array([1, 1, 3, 2, 4])
floors = np.array([1, 1, 2, 2, 1])
condition = np.array([0.48, 0.85, 0.56, 0.2, 0.1])
# Input corresponds to every entry
# for the first house in the dataset.
input = np.array([bedrooms[0], bathrooms[0], floors[0], condition[0]])
pred = neural_network(input,weights)

print(pred)

0.7140000000000001


# ***Making a Prediction with Multiple Outputs***

In [25]:
# Instead of predicting just 
# whether the house will be rente or not, 
# now we're also predicting whether
# the house need to be renovated or not
# We are making this prediction using only
# the condition of the house data point.

def ele_mul(number,vector):
    output = [0,0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

weights = [-0.2, 0.8] 

def neural_network(input, weights):
    pred = ele_mul(input,weights)
    return pred
    
condition = [0.48, 0.85, 0.56, 0.2, 0.1]
input = condition[0]
pred = neural_network(input,weights)

print(pred)

[-0.096, 0.384]


# ***Predicting with Multiple Inputs & Outputs***

In [35]:
#bedrooms condition
weights = [[0.2, -0.2], #rented/not?
            [0.1, 0.8]] #need to renovate?

def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vect,matrix):
    assert(len(vect) == len(matrix))
    output = [0,0]
    for i in range(len(vect)):
        output[i] = w_sum(vect,matrix[i])
    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input,weights)
    return pred

# This dataset is the housing 
# dataset of a society of 5
# houses

# bedrooms = number of bedrooms in a house
# bathrooms = number of bathrooms in a house
# floors = number of floors in a house
# condition = condition of house (higher the number worst the condition of house)

bedrooms =  [3, 2, 4, 3, 5]
condition = [0.48, 0.85, 0.56, 0.2, 0.1]

# Input corresponds to every entry
# for the first house of the society.

input = [bedrooms[0], condition[0]]
pred = neural_network(input,weights)

print(pred)

[0.5040000000000001, 0.684]


# ***Predicting on Predictions***

In [58]:
#bedrooms conditions
ih_wgt = [ [0.1, -0.1], #hid[0]
           [0.1, 0.3]] #hid[1]

           #hid[0] hid[1]
hp_wgt = [ [0.3, 0.004], #rented/not?
           [0.2, 0.7]] #to be renovated?

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = vect_mat_mul(input,weights[0])
    pred = vect_mat_mul(hid,weights[1])
    return pred

bedrooms =  [3, 2, 4, 3, 5]
condition = [0.48, 0.85, 0.56, 0.2, 0.1]

# Input corresponds to every entry
# for the first house of the society.

input = [bedrooms[0], condition[0]]
pred = neural_network(input,weights)

print(pred)

[0.07737600000000001, 0.3612]


# ***NumPy Version***

In [59]:
import numpy as np

#bedrooms condition
ih_wgt = np.array([ 
            [0.1, -0.1], #hid[0]
           [0.1, 0.3]]).T #hid[1]
            


# hid[0] hid[1]
hp_wgt = np.array([  
                    [0.3, 0.004], #rented/not?
                    [0.2, 0.7]]).T #to be renovated?

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):

    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred


bedrooms =  np.array([3, 2, 4, 3, 5])
condition = np.array([0.48, 0.85, 0.56, 0.2, 0.1])

input = np.array([bedrooms[0], condition[0]])

pred = neural_network(input,weights)
print(pred)

[0.077376 0.3612  ]


# **A Quick Primer on NumPy**

In [60]:
import numpy as np

a = np.array([0,1,2,3]) # a vector
b = np.array([4,5,6,7]) # another vector
c = np.array([[0,1,2,3], # a matrix
              [4,5,6,7]])

d = np.zeros((2,4)) # (2x4 matrix of zeros)
e = np.random.rand(2,5) # random 2x5
# matrix with all numbers between 0 and 1

print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.02174913 0.43127535 0.34439352 0.90742077 0.96211843]
 [0.03346666 0.54290302 0.31236018 0.65180825 0.95883748]]


In [61]:
print(a * 0.1) # multiplies every number in vector "a" by 0.1
      
print(c * 0.2) # multiplies every number in matrix "c" by 0.2
      
print(a * b) # multiplies elementwise between a and b (columns paired up)
      
print(a * b * 0.2) # elementwise multiplication then multiplied by 0.2
      
print(a * c) # since c has the same number of columns as a, this performs
# elementwise multiplication on every row of the matrix "c"

print(a * e) # since a and e don't have the same number of columns, this
# throws a "Value Error: operands could not be broadcast together with.."


[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


ValueError: ignored

In [62]:
a = np.zeros((1,4)) # vector of length 4
b = np.zeros((4,3)) # matrix with 4 rows & 3 columns

c = a.dot(b)
print(c.shape)

(1, 3)


In [63]:
a = np.zeros((2,4)) # matrix with 2 rows and 4 columns
b = np.zeros((4,3)) # matrix with 4 rows & 3 columns

c = a.dot(b)
print(c.shape) # outputs (2,3)

e = np.zeros((2,1)) # matrix with 2 rows and 1 columns
f = np.zeros((1,3)) # matrix with 1 row & 3 columns

g = e.dot(f)
print(g.shape) # outputs (2,3)

h = np.zeros((5,4)).T # matrix with 4 rows and 5 columns
i = np.zeros((5,6)) # matrix with 6 rows & 5 columns

j = h.dot(i)
print(j.shape) # outputs (4,6)

h = np.zeros((5,4)) # matrix with 5 rows and 4 columns
i = np.zeros((5,6)) # matrix with 5 rows & 6 columns
j = h.dot(i)
print(j.shape) # throws an error

(2, 3)
(2, 3)
(4, 6)


ValueError: ignored